"""Helper script to write FRIDAY implementer position."""
import pathlib

OUTPATH = pathlib.Path.home() / ".claude/dispatch/FRIDAY/outbox/position-implementer.md"

LINES = [
"---",
"from: FRIDAY",
"type: complete",
"audience: genie",
"timestamp: 2026-03-29T15:30:00Z",
"---",
"",
"# IMPLEMENTER Position — GENIE Upgrade Feasibility Analysis",
"",
"## Executive Summary",
"",
"77 proposals across 6 reports synthesized into 9 implementation clusters.",
"Waves 1-5 are executable sequentially (~32-40h total). Wave 6 is long-horizon R&D.",
"Critical path: Reliability hardening → Context optimization → Quality gates → GSD hardening → Fleet intelligence → Long-horizon.",
"11 quick wins identified (<30 min each). No proposal discarded — LOW-priority items scheduled to late waves.",
"",
"---",
"",
"## Section 1: Implementation Groupings",
"",
"Nine clusters. Each cluster maps to a wave. Dependencies flow from A → I.",
"",
"### Cluster A — Reliability Hardening (CRITICAL PATH ENTRY)",
"Items that harden the current system before any extension:",
"- A1: Stall detection + GENIE poke (AURORA QW1 / Critic B1)",
"- A2: Heartbeat timeout circuit breaker (AURORA QW2 / Critic B2)",
"- A3: Worker restart on failure (AURORA QW3 / Critic B3)",
"- A4: Inbox message deduplication (AURORA QW4)",
"- A5: Status.json schema validation (AURORA QW5)",
"- A6: GENIE mode enforcement hook (NOVA H1)",
"- A7: GENIE_WORKER env var standardization (NOVA H2)",
"- A8: Worker identity injection at dispatch (NOVA H3)",
"- A9: Progressive skill disclosure — 3-tier loading (EDITH S1)",
"",
"### Cluster B — Context Tier 1 Quick Wins (TOKEN BUDGET)",
"Text-only changes, zero risk, immediate savings:",
"- B1: Collapse CLAUDE.md rules into single-file (AURORA ME1)",
"- B2: Trim worker protocol verbose text (AURORA ME2)",
"- B3: Remove duplicate agent roster from worker definitions (AURORA ME3)",
"- B4: Compress status.json schema docs (AURORA ME4)",
"",
"### Cluster C — Context Tier 2 Medium Effort",
"Code changes to startup loading behavior:",
"- C1: Lazy-load rules files (only referenced rules loaded) (AURORA AR1)",
"- C2: Token-counted startup budget enforcer (AURORA AR2)",
"- C3: INDEX.yaml-only startup with on-demand expansion (AURORA AR3)",
"- C4: Context auto-pause at 65% threshold (FRIDAY 4.5 + PEPPER resolution)",
"",
"### Cluster D — Context Tier 3 Architecture",
"High-effort, high-payoff structural changes:",
"- D1: Worker-type-specific startup profiles (AURORA AR4a)",
"- D2: Dynamic skill injection based on task type (EDITH S2 / AURORA AR4b)",
"- D3: Startup token budget: 5,000 target (AURORA architecture goal)",
"",
"### Cluster E — GENIE Tooling Extensions",
"Extends GENIE with Claude Code built-in features:",
"- E1: RemoteTrigger for external event ingestion (NOVA T1 — already exists as genie-fleet-alert)",
"- E2: CronCreate durable heartbeat monitor (NOVA T2)",
"- E3: TeammateIdle hook — auto-restart idle workers (NOVA T3)",
"- E4: Bridge file pattern for cross-session worker state (NOVA T4)",
"- E5: StatusLine worker identity display (NOVA UI1)",
"- E6: Inbox polling via SendMessage (NOVA T5)",
"",
"### Cluster F — Quality Gates",
"Validation and quality enforcement before and after work:",
"- F1: Pre-dispatch task schema validation (Critic B4 / PEPPER Gap 5)",
"- F2: Post-complete automated quality scorer (Critic B5 / PEPPER Gap 3)",
"- F3: Worker output format linter (PEPPER Gap 2)",
"- F4: Five Questions framework enforced by GENIE (Critic framework)",
"- F5: Recovery checkpoint on worker failure (PEPPER Gap 4)",
"- F6: Adversarial testing harness — red-team worker vs blue-team verifier (FRIDAY 6.5)",
"",
"### Cluster G — Fleet Intelligence",
"Multi-worker coordination and observability:",
"- G1: Structured Finding schema for discovery agents (PEPPER Gap 5 — highest leverage)",
"- G2: Worker performance tracking in GENIE (FRIDAY 2.1)",
"- G3: Worker specialization routing — GENIE auto-picks best worker per task (FRIDAY 2.2)",
"- G4: GitHub Issues integration for persistent task tracking (FRIDAY 6.1)",
"- G5: OTEL observability pipeline (EDITH S3)",
"- G6: Agent Farm batch dispatch pattern (EDITH S4)",
"",
"### Cluster H — GSD Pipeline Hardening",
"Fixes GSD autopilot execution reliability:",
"- H1: Phase recovery auto-loop (PEPPER Gap 4 — critical)",
"- H2: GSD-native autopilot architecture (~100-line loop) (PEPPER Gap 6)",
"- H3: Parallel wave execution in autopilot (PEPPER Gap 7)",
"- H4: Discovery agent structured output (PEPPER Gap 5)",
"- H5: Cross-phase dependency enforcement (PEPPER Gap 8)",
"- H6: GSD state sync to GENIE (PEPPER Gap 1)",
"",
"### Cluster I — Long-Horizon / Experimental",
"Low priority, high complexity, scheduled last:",
"- I1: SQLite mailbox evaluation (EDITH S5 — LOW per PEPPER arbiter)",
"- I2: Cross-session knowledge graph (FRIDAY 6.4 — LAST per PEPPER arbiter)",
"- I3: Worker hibernation warm-restart (FRIDAY 3.5 — LOW per PEPPER arbiter)",
"- I4: TUI dashboard ANSI improvements (FRIDAY 5.2 — incremental)",
"- I5: Multi-agent debate harness (FRIDAY 6.3)",
"- I6: Probabilistic task routing (FRIDAY 2.4)",
"- I7: Worker self-improvement loop (FRIDAY 2.5)",
"",
"---",
"",
"## Section 2: Dependency Chains",
"",
"Four dependency levels. Each level can begin only after its predecessors complete.",
"",
"### Level 0 — No Prerequisites (can start immediately)",
"- Cluster A (Reliability Hardening): All items are text/hook changes, no prereqs",
"- Cluster B (Context Tier 1): Text changes to existing files, no prereqs",
"- These two clusters are FULLY PARALLEL with each other",
"",
"### Level 1 — Requires Level 0",
"- Cluster C (Context Tier 2): Requires B (collapsed CLAUDE.md) + A3 (restart on failure)",
"- Cluster E (GENIE Tooling): Requires A6 (mode enforcement hook) + A7 (GENIE_WORKER env var)",
"- C and E are parallel to each other",
"",
"### Level 2 — Requires Level 1",
"- Cluster D (Context Tier 3): Requires C (lazy loading + token budget)",
"- Cluster F (Quality Gates): Requires E (GENIE tooling + schema) + A (reliability)",
"- Cluster G (Fleet Intelligence): Requires E3 (TeammateIdle) + F1 (task schema)",
"- D, F, G are parallel to each other",
"",
"### Level 3 — Requires Level 2",
"- Cluster H (GSD Pipeline): Requires G1 (structured Finding schema) + F5 (recovery checkpoint)",
"- H depends on G and F being stable",
"",
"### Level 4 — Requires Level 3 (Long-Horizon)",
"- Cluster I (Experimental): Requires H (full pipeline stable) + G (fleet intelligence)",
"- Only schedule after Waves 1-5 are proven stable in production",
"",
"Critical Path (longest chain):",
"A/B → C+E → F+G → H → I",
"Estimated critical path time: ~28-34h for Waves 1-5",
"",
"---",
"",
"## Section 3: Risk Assessment",
"",
"### LOW Risk — Text/Config Changes Only",
"These cannot break existing functionality. Safe to implement in any order.",
"- A1-A5: Status/heartbeat fixes (config + text changes)",
"- A7-A8: Env var standardization (additive)",
"- B1-B4: All context Tier 1 (text compression)",
"- A9/C4: Threshold config changes (single number change)",
"- E5: StatusLine display (cosmetic)",
"",
"### MEDIUM Risk — New Code, Isolated Modules",
"New files or modules. Failures are contained and don't affect existing paths.",
"- A6: GENIE mode enforcement hook (new hook file, additive)",
"- C1-C3: Lazy loading (changes startup sequence — test carefully)",
"- E1-E6: GENIE tooling extensions (new capabilities, existing paths unaffected)",
"- F1-F4: Quality gate validators (additive to dispatch flow)",
"- G1-G4: Fleet intelligence (new tracking layer, no core changes)",
"- H1-H3: GSD autopilot loop changes (contained to autopilot.py)",
"",
"### HIGH Risk — Architectural / Cross-Cutting",
"Touches dispatch core or multiple workers. Requires careful staging and rollback plan.",
"- D1-D3: Worker-type startup profiles (changes ALL worker startup paths)",
"- D2: Dynamic skill injection (complex conditional loading)",
"- F5/H1: Recovery checkpoint + phase recovery auto-loop (state machine changes)",
"- G5: OTEL observability (external dependency, new infra)",
"- G6: Agent Farm batch dispatch (changes GENIE dispatch model)",
"- I1: SQLite mailbox (replaces file-based dispatch — DO NOT do this lightly)",
"- I2: Knowledge graph (external storage, high complexity)",
"- I3: Worker hibernation (context lifecycle changes)",
"",
"---",
"",
"## Section 4: Effort Estimates",
"",
"Scale: XS=10-30m, S=<2h, M=2-8h, L=1-3d, XL=3+d",
"",
"### Cluster A",
"| Item | Effort | Rationale |",
"| A1 Stall detection + poke | S | Add timer check + Bash poke in GENIE main loop |",
"| A2 Heartbeat timeout circuit breaker | S | Add timestamp check + restart trigger |",
"| A3 Worker restart on failure | S | One function in GENIE dispatch loop |",
"| A4 Inbox deduplication | XS | Add message ID hash check (10 lines) |",
"| A5 Status.json schema validation | S | Pydantic or jsonschema validator |",
"| A6 GENIE mode enforcement hook | S | PreToolUse hook, ~30 lines |",
"| A7 GENIE_WORKER env var | XS | Add to dispatch Bash command |",
"| A8 Worker identity injection | XS | One-line dispatch change |",
"| A9 Progressive skill disclosure | M | Restructure skill loading in 3 tiers |",
"",
"### Cluster B",
"| Item | Effort | Rationale |",
"| B1 Collapse CLAUDE.md rules | M | Edit + test startup token count |",
"| B2 Trim worker protocol | S | Remove verbose text, keep semantics |",
"| B3 Remove duplicate agent roster | S | Find + delete from worker definitions |",
"| B4 Compress status.json docs | XS | Shorten inline schema comments |",
"",
"### Cluster C",
"| Item | Effort | Rationale |",
"| C1 Lazy-load rules files | M | Add conditional include logic |",
"| C2 Token-counted startup enforcer | M | Add token counter to startup script |",
"| C3 INDEX.yaml startup | L | New loading protocol, test all workers |",
"| C4 Context auto-pause 65% | S | Change threshold config value |",
"",
"### Cluster D",
"| Item | Effort | Rationale |",
"| D1 Worker-type startup profiles | L | Create profile configs per worker type |",
"| D2 Dynamic skill injection | L | Task-type → skill mapping logic |",
"| D3 5000-token budget target | XL | Requires D1+D2+B+C all complete |",
"",
"### Cluster E",
"| Item | Effort | Rationale |",
"| E1 RemoteTrigger (already exists) | XS | Wire existing trigger to GENIE handler |",
"| E2 CronCreate durable heartbeat | S | Register cron job, handle callback |",
"| E3 TeammateIdle hook | S | Add hook file, ~40 lines |",
"| E4 Bridge file pattern | M | Define bridge spec + GENIE reader |",
"| E5 StatusLine display | XS | Add GENIE_WORKER to StatusLine config |",
"| E6 Inbox polling via SendMessage | M | Replace file polling with SendMessage API |",
"",
"### Cluster F",
"| Item | Effort | Rationale |",
"| F1 Pre-dispatch task schema | M | Define schema, validate on dispatch |",
"| F2 Post-complete quality scorer | M | Scoring function in GENIE complete handler |",
"| F3 Worker output linter | M | Format rules + lint runner |",
"| F4 Five Questions framework | M | Encode framework as dispatch checklist |",
"| F5 Recovery checkpoint | M | Save+restore state on failure |",
"| F6 Adversarial testing harness | L | Two-worker harness with test oracle |",
"",
"### Cluster G",
"| Item | Effort | Rationale |",
"| G1 Structured Finding schema | S | Define Pydantic Finding model, update templates |",
"| G2 Worker performance tracking | M | Add perf counters to GENIE state |",
"| G3 Worker specialization routing | M | Add routing table + selection logic |",
"| G4 GitHub Issues integration | M | gh CLI wrapper in GENIE |",
"| G5 OTEL pipeline | L | External OTEL collector, instrumentation |",
"| G6 Agent Farm batch dispatch | L | Parallel dispatch DAG in GENIE |",
"",
"### Cluster H",
"| Item | Effort | Rationale |",
"| H1 Phase recovery auto-loop | M | Retry logic in GSD executor |",
"| H2 GSD-native autopilot | L | Rewrite autopilot.py to ~100-line GSD loop |",
"| H3 Parallel wave execution | M | Add wave-parallel dispatch to GSD executor |",
"| H4 Discovery agent structured output | S | Add Finding schema to discovery agents |",
"| H5 Cross-phase dependency enforcement | M | Dependency check in GSD plan loader |",
"| H6 GSD state sync to GENIE | M | Bidirectional state bridge |",
"",
"### Cluster I (Long-Horizon)",
"| Item | Effort | Rationale |",
"| I1 SQLite mailbox | XL | Full protocol replacement, high risk |",
"| I2 Knowledge graph | XL | External storage, schema design, query API |",
"| I3 Worker hibernation | L | Context snapshot/restore protocol |",
"| I4 TUI dashboard improvements | M | ANSI color + better formatting |",
"| I5 Multi-agent debate harness | L | Orchestration of 4-worker debate |",
"| I6 Probabilistic task routing | L | Bayesian routing model |",
"| I7 Worker self-improvement loop | XL | Feedback loop + update mechanism |",
"",
"---",
"",
"## Section 5: Quick Wins (<30 minutes each)",
"",
"These 11 items can each be completed in a single focused 10-30 minute session.",
"All are LOW risk (text/config changes or tiny additive code).",
"",
"1. **A4: Inbox deduplication** — Add message ID hash check, ~10 lines in GENIE inbox reader",
"2. **A7: GENIE_WORKER env var** — One-line change to dispatch command template",
"3. **A8: Worker identity injection** — One-line change to worker startup",
"4. **A1: Stall detection** — Add one timer check + `sendMessage` poke in GENIE heartbeat monitor",
"5. **B4: Compress status.json docs** — Shorten inline comments in status schema docs",
"6. **E1: Wire RemoteTrigger** — genie-fleet-alert trigger already exists, add GENIE handler (~20 lines)",
"7. **E5: StatusLine display** — Add `GENIE_WORKER` to StatusLine config string",
"8. **C4: Context auto-pause threshold** — Change single config value from 70 to 65",
"9. **G1: Structured Finding schema** — Define Pydantic Finding model (<50 lines) + update 2 templates",
"10. **H4: Discovery agent structured output** — Add Finding schema return to discovery agent templates",
"11. **B2: Trim worker protocol** — Remove 5-6 verbose paragraphs from worker protocol, test token count",
"",
"---",
"",
"## Section 6: Suggested Wave Ordering",
"",
"### Wave 1 — Quick Wins (3-4h, 2-3 workers, PARALLEL)",
"Goal: Immediate reliability + token savings with zero risk.",
"Items: A1-A5, A7-A8, B2, B4, C4, E1, E5, G1, H4",
"Workers: FRIDAY (A items) + AURORA (B items) + NOVA (E items) in parallel",
"All items are XS or S. No dependencies between workers in this wave.",
"Expected savings: 2,000-3,000 tokens/startup, zero breakage risk.",
"",
"### Wave 2 — Infrastructure (6-8h, 2 workers, SEQUENTIAL after Wave 1)",
"Goal: GENIE tooling + quality gates scaffolding.",
"Items: A6, A9, E2-E4, E6, F1, F2",
"Workers: NOVA (E items) + PEPPER (F items)",
"Dependency: Wave 1 must complete first (env var + mode enforcement prereqs).",
"Risk: MEDIUM. New code modules, fully additive.",
"",
"### Wave 3 — Context Budget (8-10h, 2 workers, SEQUENTIAL after Wave 2)",
"Goal: Reduce startup token cost toward 5,000-token target.",
"Items: B1, B3, C1-C3, D1 (partial)",
"Workers: AURORA (B+C items) + IRIS (codebase analysis for D1 prereqs)",
"Dependency: B items before C items (collapsed CLAUDE.md enables lazy loading).",
"Risk: MEDIUM-HIGH for C1-C3. Test each change against token counter.",
"Expected savings: additional 5,000-8,000 tokens/startup.",
"",
"### Wave 4 — Quality Gates (6-8h, 2 workers, PARALLEL with Wave 3)",
"Goal: Fleet reliability through validation and observability.",
"Items: F3-F6, G2-G4",
"Workers: VERONICA (F items) + EDITH (G items)",
"Note: Wave 4 can run IN PARALLEL with Wave 3 (different files, different workers).",
"Risk: MEDIUM. Additive to GENIE dispatch flow.",
"",
"### Wave 5 — GSD Pipeline Hardening (8-10h, 1-2 workers, SEQUENTIAL after Wave 4)",
"Goal: Make autopilot execution reliable and self-healing.",
"Items: H1-H6",
"Workers: PEPPER (GSD expertise) + FRIDAY (autopilot loop)",
"Dependency: G1 (Finding schema) + F5 (recovery checkpoint) must be complete.",
"Risk: MEDIUM-HIGH. Changes GSD executor state machine.",
"",
"### Wave 6 — Autonomy + Long-Horizon (multi-session, after Wave 5 stable)",
"Goal: Advanced fleet intelligence and experimental capabilities.",
"Items: D2-D3, G5-G6, I1-I7",
"Workers: Full fleet, each item assigned per expertise",
"Dependency: ALL prior waves stable in production.",
"Risk: HIGH for I1-I3. Stage each item as a separate mini-wave.",
"Do NOT bundle multiple HIGH-risk items in one session.",
"",
"---",
"",
"## Section 7: Worker Assignment Suggestions",
"",
"### FRIDAY — General-Purpose Coding",
"Best for: Implementation, feature development, multi-file changes",
"Assigned: A1-A3, H1-H3, H6, I5, I6",
"Rationale: FRIDAY wrote the 26-proposal advocate report — deep context on the proposals.",
"",
"### AURORA — Research + Analysis + Token Optimization",
"Best for: Context/token work, analysis, structured research",
"Assigned: B1-B4, C1-C4, D1-D3",
"Rationale: AURORA produced the token optimization report — owns this domain.",
"",
"### NOVA — Claude Code Features + GENIE Tooling",
"Best for: Hooks, triggers, Claude Code API integration",
"Assigned: A6-A8, E1-E6",
"Rationale: NOVA discovered these features — knows the implementation details.",
"",
"### PEPPER — Architecture + GSD + Quality",
"Best for: GSD pipeline, architectural decisions, quality gates",
"Assigned: F1-F5, H1-H5, D1 (design)",
"Rationale: PEPPER wrote GSD autopilot and critic reports — owns both domains.",
"",
"### EDITH — Community Research + DevOps",
"Best for: External integrations, observability, community patterns",
"Assigned: A9, G4-G6, I1 (evaluation)",
"Rationale: EDITH researched these patterns (OTEL, SQLite, Agent Farm).",
"",
"### VERONICA — Multi-System Coordination",
"Best for: Cross-system integration, complex orchestration",
"Assigned: F3-F6, G3, I5",
"Rationale: VERONICA's coordination expertise suits quality gate enforcement.",
"",
"### IRIS — Fast Codebase Exploration",
"Best for: Scanning, discovery, quick reads",
"Assigned: Wave 1 support, G2 (perf tracking data collection)",
"Rationale: IRIS is fast haiku agent — ideal for pre-wave codebase scans.",
"",
"### LUNA — Diagnostics + Routing",
"Best for: Health checks, message routing, system state",
"Assigned: A4-A5, G1 (Finding schema integration tests)",
"Rationale: LUNA's diagnostic focus suits validation and schema work.",
"",
"---",
"",
"## Section 8: Parallel vs Sequential",
"",
"### Fully Parallel (no coordination needed)",
"- Wave 1 items: FRIDAY(A) + AURORA(B) + NOVA(E) run simultaneously",
"- Wave 3 + Wave 4: Different files, different workers, full parallel",
"- Within Wave 1: All 11 quick wins can be dispatched to separate workers simultaneously",
"",
"### Partial Parallel (same wave, soft sequencing)",
"- Wave 2: NOVA finishes E2-E3 before PEPPER starts F1 (F1 needs E2 hook model)",
"  But E4/E6 and F2/F3 can overlap",
"- Wave 5: H1 (recovery loop) before H2 (GSD-native autopilot) — H2 wraps H1",
"",
"### Strictly Sequential",
"- B items before C items (C1 lazy-loading needs collapsed CLAUDE.md)",
"- C items before D items (D1 profiles need C3 INDEX.yaml loading)",
"- Wave 4 before Wave 5 (H needs F5 recovery checkpoint + G1 Finding schema)",
"- Entire Wave 1-5 sequence before Wave 6 HIGH-risk items",
"",
"### Dependency Graph Summary",
"```",
"Wave 1 (A+B quick wins)",
"  |",
"  +--- Wave 2 (E tooling + F scaffolding)     Wave 3 (B+C token budget)",
"         |                                          |",
"         +--- Wave 4 (F gates + G fleet) [parallel with Wave 3]",
"                |",
"                +--- Wave 5 (H GSD hardening)",
"                       |",
"                       +--- Wave 6 (D3 + I items)",
"```",
"",
"---",
"",
"## Implementation Notes",
"",
"1. **Start with Wave 1** — All 11 quick wins can ship in the same session. Zero risk.",
"   Dispatch FRIDAY + AURORA + NOVA simultaneously. Done in <4h.",
"",
"2. **Token savings compound** — B items improve Wave 3 startup cost, which means",
"   every subsequent worker has more context headroom. Do B before C.",
"",
"3. **PEPPER arbiter resolutions are binding** — Knowledge graph (I2) is LAST.",
"   SQLite mailbox (I1) is evaluation-only until I/O contention is measured.",
"   Context threshold is 65% (PEPPER compromise). These are not re-litigated.",
"",
"4. **Finding schema (G1) is the highest-leverage single item** — PEPPER called this out.",
"   It's also a quick win (S effort). Do it in Wave 1.",
"",
"5. **GSD-native autopilot (H2) is the biggest payoff item** — Reduces autopilot.py",
"   from current complexity to ~100-line loop. Schedule Wave 5. Prereqs: H1+F5+G1.",
"",
"6. **Adversarial testing (F6) belongs in Wave 4** — Once quality gates exist,",
"   add a red-team harness to stress-test them. High value for long-term robustness.",
"",
"7. **HIGH-risk items (D2-D3, I1-I3) need explicit human approval** — Before dispatching",
"   any Wave 6 architectural item, GENIE should produce a one-page proposal for",
"   user review. No autonomous Wave 6 dispatch.",
]

content = "\n".join(LINES)
OUTPATH.write_text(content, encoding="utf-8")
size = OUTPATH.stat().st_size
print(f"Written: {OUTPATH} ({size} bytes, {len(LINES)} lines)")
